In [1]:
#Python NumPy (Array, Random, Math)

In [3]:
# Write a Python program to print the NumPy version in your system.

import numpy as np
print(np.__version__)

1.20.3


In [7]:
# Write a Python program to reverse an array (first element becomes last).

import numpy as np
x= np.arange(1,21)
print (x)
x = x[::-1]
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [11]:
# Write a Python program to convert a list and tuple into arrays.


import numpy as np
lst = [1, 2, 3, 4, 5, 6, 7, 8]
print(lst)
print(type(lst))
print(np.asarray(lst))
tpl = (1,2,3,4,5,6,7,8)
print(tpl)
print(type(tpl))
print(np.asarray(tpl))

[1, 2, 3, 4, 5, 6, 7, 8]
<class 'list'>
[1 2 3 4 5 6 7 8]
(1, 2, 3, 4, 5, 6, 7, 8)
<class 'tuple'>
[1 2 3 4 5 6 7 8]


In [14]:
# Write a Python program to find common values between two arrays.


import numpy as np
ar1 = np.array([0,10,20,30,40,50,60])
print(ar1)
ar2 = [10,30,40,60,70,80]
print(ar2)
print(np.intersect1d(ar1, ar2))

[ 0 10 20 30 40 50 60]
[10, 30, 40, 60, 70, 80]
[10 30 40 60]


In [34]:
# Write a Python program compare two arrays using numpy.
import numpy as np
ar1 = np.array([0,10,20,30,40,50,60])
print(ar1)
ar2 = [10,30,40,60,70,80,90]
print(ar2)
print(np.equal(ar1, ar2))
print(np.greater(ar1, ar2))
print(np.greater_equal(ar1, ar2))
print(np.less(ar1, ar2))
print(np.less_equal(ar1, ar2))

[ 0 10 20 30 40 50 60]
[10, 30, 40, 60, 70, 80, 90]
[False False False False False False False]
[False False False False False False False]
[False False False False False False False]
[ True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True]


In [38]:
# Write a Python program to change the dimension of an array.

import numpy as np
ar1 = np.array([10,20,30,40,50,60,70,80,90])
print(ar1)
print(ar1.shape)
ar1.shape = (3,3)
print(ar1)

[10 20 30 40 50 60 70 80 90]
(9,)
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [46]:
# Write a Python program (using numpy) to sum of all the multiples 
#of 3 or 5 below 100.

import numpy as np
x = np.arange(1,100)
n= x[(x % 3 == 0) | (x % 5 == 0)]
print(n)
print(n.sum())

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


In [44]:
# Write a Python program to convert a NumPy array into Python list structure. 

import numpy as np
x= np.arange(6).reshape(3, 2)
print(x)
print(x.tolist())

[[0 1]
 [2 3]
 [4 5]]
[[0, 1], [2, 3], [4, 5]]


In [51]:
# Write a Python program to how to add an extra column to a numpy array.


import numpy as np
x = np.array([[10,20,30], [40,50,60]])
print(x)
y = np.array([[100], [200]])
print(y)
z = np.append(x,y, axis =1)
print(z)

[[10 20 30]
 [40 50 60]]
[[100]
 [200]]
[[ 10  20  30 100]
 [ 40  50  60 200]]


In [52]:
# Write a Python program to check whether the numpy array is empty or not.


import numpy as np
x = np.array([2, 3])
y = np.array([])
print(x.size)
print(y.size)

2
0


In [69]:
# Write a Python program to normalize a 3x3 random matrix.


import numpy as np
x= np.random.random((3,3))
print(x)
xmax = x.max()
xmin = x.min()
x = (x - xmin)/(xmax - xmin)
print(x)

[[0.27600718 0.99113173 0.5614232 ]
 [0.37624324 0.62080725 0.70067775]
 [0.16675249 0.92170156 0.95730146]]
[[0.13252965 1.         0.47874898]
 [0.25411939 0.55078384 0.64766947]
 [0.         0.91577885 0.95896274]]


In [80]:
# How to ignore all numpy warnings (not recommended)?


import numpy as np
np.seterr(all="ignore")

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}